---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: airflow
  labels:
    provider: helm
    crossplane.io/xrd: lbxairflow.addons.launchboxhq.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: addons.launchboxhq.io/v1alpha1
    kind: LbxAirflow
  resources:
    - name: airflow
      base:
        apiVersion: helm.crossplane.io/v1alpha1
        kind: Release
        metadata:
          name: airflow
        spec:
          forProvider:
            chart:
              name: airflow
              repository: https://charts.min.io/
              version: 14.1.3
            namespace: default
            values: {}
            valuesFrom: []
            set: []
            patches: []
