---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rabbitmq
  labels:
    provider: helm
    crossplane.io/xrd: lbxrabbitmq.addons.launchboxhq.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: addons.launchboxhq.io/v1alpha1
    kind: LbxRabbitMQ
  resources:
    - name: rabbitmq
      base:
        apiVersion: helm.crossplane.io/v1alpha1
        kind: Release
        metadata:
          name: rabbitmq
        spec:
          forProvider:
            chart:
              name: rabbitmq
              repository: https://charts.min.io/
              version: 11.5.1
            namespace: default
            values: {}
            valuesFrom: []
            set: []
            patches: []
