---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: lbxrabbitmq.addons.launchboxhq.io
spec:
  group: addons.launchboxhq.io
  names:
    kind: LbxRabbitMQ
    plural: lbxrabbitmqs
  claimNames:
    kind: RabbitMQ
    plural: rabbitmqs
  connectionSecretKeys:
    - password
    - endpoint
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "The OpenAPIV3Schema of this Composite Resource Definition."
              properties: {}
              required: []
