---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vault
  labels:
    provider: helm
    crossplane.io/xrd: lbxvaultcluster.addons.launchboxhq.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: addons.launchboxhq.io/v1alpha1
    kind: LbxVaultCluster
  resources:
    - name: vault
      base:
        apiVersion: helm.crossplane.io/v1alpha1
        kind: Release
        metadata:
          name: vault
        spec:
          forProvider:
            chart:
              name: vault
              repository: oci://registry-1.docker.io/bitnamicharts
              version: 0.1.2
            namespace: default
            values: {}
            valuesFrom: []
            set: []
            patches:
              - type: fromCompositeFieldPath
                fromFieldPath: spec.password
                toFieldPath: spec.forProvider.values.auth.password
              - type: fromCompositeFieldPath
                fromFieldPath: spec.size
                toFieldPath: spec.forProvider.values.master.persistence.size
