---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: lbxminio.addons.launchboxhq.io
spec:
  group: addons.launchboxhq.io
  names:
    kind: LbxMinio
    plural: lbxminios
  claimNames:
    kind: Minio
    plural: minios
  connectionSecretKeys:
    - password
    - endpoint
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "The OpenAPIV3Schema of this Composite Resource Definition."
              properties: {}
              required: []
