---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mongodb
  labels:
    provider: helm
    crossplane.io/xrd: lbxmongodb.addons.launchboxhq.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: addons.launchboxhq.io/v1alpha1
    kind: LbxMongoDB
  resources:
    - name: mongodb
      base:
        apiVersion: helm.crossplane.io/v1alpha1
        kind: Release
        metadata:
          name: mongodb
        spec:
          forProvider:
            chart:
              name: mongodb
              repository: oci://registry-1.docker.io/bitnamicharts
              version: 13.10.3
            namespace: default
            values: {}
            valuesFrom: []
            set: []
            patches: []
