---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: redis
  labels:
    provider: helm
    crossplane.io/xrd: lbxrediscluster.addons.launchboxhq.io
spec:
  writeConnectionSecretsToNamespace: lbx-system
  compositeTypeRef:
    apiVersion: addons.launchboxhq.io/v1alpha1
    kind: LbxRedisCluster
  resources:
    - name: redis
      base:
        apiVersion: helm.crossplane.io/v1alpha1
        kind: Release
        metadata:
          name: redis
        spec:
          forProvider:
            chart:
              name: redis
              repository: oci://registry-1.docker.io/bitnamicharts
              version: 17.10.1
            namespace: default
            values:
              architecture: standalone
              auth:
                enabled: true
                password: ""
              metrics:
                enabled: true
              master:
                persistence:
                  enabled: true
                  size: 2Gi
            valuesFrom: []
            set: []
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.forProvider.values.master.persistence.size
        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.namespace
          toFieldPath: metadata.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef.name
  functions:
    - name: secret-extracter
      type: Container
      container:
        image: ghcr.io/launchboxio/secret-extracter-function:sha-1cba4ad