---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: redis.addons.launchboxhq.io
spec:
  group: addons.launchboxhq.io
  names:
    kind: LbxRedisCluster
    plural: lbxredisclusters
  claimNames:
    kind: RedisCluster
    plural: redisclusters
  connectionSecretKeys:
    - password
    - endpoint
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "The OpenAPIV3Schema of this Composite Resource Definition."
              properties:
                password:
                  type: string
                  description: "Password for the redis cluster"
                parameters:
                  type: object
                  properties:
                    storageGB:
                      type: integer
                      description: "The desired storage capacity of the database, in GB."
                  required:
                    - storageGB
              required: []
