---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: lbxredisclusters.addons.launchboxhq.io
spec:
  group: addons.launchboxhq.io
  names:
    kind: LbxRedisCluster
    plural: lbxredisclusters
  claimNames:
    kind: RedisCluster
    plural: redisclusters
  connectionSecretKeys:
    - password
    - endpoint
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "The OpenAPIV3Schema of this Composite Resource Definition."
              properties:
                password:
                  type: string
                  description: "Password for the redis cluster"
                size:
                  type: string
                  description: "The desired storage capacity of the database, in GB."
                  default: "2Gi"
              required:
                - password

# {"name":"lbxrediscluster.addons.launchboxhq.io"}, "uid": "a80c6ee8-4d9e-4b86-94a4-5411c7439356", "version": "2866370", "name": "lbxrediscluster.addons.launchboxhq.io", "error": "cannot create object: CustomResourceDefinition.apiextensions.k8s.io \"lbxrediscluster.addons.launchboxhq.io\" is invalid: metadata.name: Invalid value: \"lbxrediscluster.addons.launchboxhq.io\": must be spec.names.plural+\".\"+spec.group"}