---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: lbxredisclusters.addons.launchboxhq.io
spec:
  group: addons.launchboxhq.io
  names:
    kind: LbxRedisCluster
    plural: lbxredisclusters
  claimNames:
    kind: RedisCluster
    plural: redisclusters
  connectionSecretKeys:
    - password
    - endpoint
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "The OpenAPIV3Schema of this Composite Resource Definition."
              properties:
                providerConfigRef:
                  type: string
                  description: "The provider to use for deployment"
                password:
                  type: string
                  description: "Password for the redis cluster"
                size:
                  type: string
                  description: "The desired storage capacity of the database, in GB."
                  default: "2Gi"
              required: []
