---
name: Main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  packages: write

jobs:
  publish:
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          channel: stable
          version: current
          command: build configuration -f ${{ github.workspace }}/packages/redis
      - name: Push
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          command: push configuration -f ${{ github.workspace }}/packages/redis ghcr.io/launchboxio/addons/packages/redis
